### ISSUE TITLE
Build failed: Illegal equational constraint a ~ Char

### ISSUE THREAD

**Issue by lukabot** [system-f/fp-course#402]
#401 breaks the build on 8.6.5
Maybe we should update .ghci or relevant files also?

```
$ ghci

GHCi, version 8.6.5: http://www.haskell.org/ghc/  :? for help
package flags have changed, resetting and loading new packages...
package flags have changed, resetting and loading new packages...
[ 1 of 48] Compiling Course.Core      ( src/Course/Core.hs, interpreted )
[ 2 of 48] Compiling Course.Contravariant ( src/Course/Contravariant.hs, interpreted )
[ 3 of 48] Compiling Course.ExactlyOne ( src/Course/ExactlyOne.hs, interpreted )
[ 4 of 48] Compiling Course.Optional  ( src/Course/Optional.hs, interpreted )
[ 5 of 48] Compiling Course.List      ( src/Course/List.hs, interpreted )

src/Course/List.hs:662:10: error:
    • Illegal equational constraint a ~ Char
      (Use GADTs or TypeFamilies to permit this)
    • In the context: a ~ Char
      While checking an instance declaration
      In the instance declaration for ‘IsString (List a)’
    |
662 | instance (a ~ Char) => IsString (List a) where
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Failed, four modules loaded.

<no location info>: error:
    Could not find module ‘Test.Loader’
    It is not a module in the current program, or in any known package.
```

**Comment by lukabot** [comment]
Closing, #403
